version: '3'

services:
  postgres:
    image: postgres:10.5-alpine
    container_name: rotten_tomatoes_postgres
    ports:
      - 9000:5432
    environment:
      - POSTGRES_USER=rotten_tomatoes_user
      - POSTGRES_DB=rotten_tomatoes